<script setup>
import { onMounted, ref, computed } from 'vue'
import { api } from '../services/api'
const products=ref([]);const categories=ref([]);const search=ref('');const status=ref('');const category=ref('');const loading=ref(true)
const fallback=[{id:1,name:'طاولة جانبية مودرن',sku:'VORA-001',brand:'VORA Home',price:1290,stock:12,status:'PUBLISHED',category_name:'أثاث خارجي'},{id:2,name:'كرسي Lounge فاخر',sku:'VORA-002',brand:'VORA Home',price:3490,stock:7,status:'PUBLISHED',category_name:'كراسي'},{id:3,name:'مصباح أرضي Minimal',sku:'VORA-003',brand:'VORA Lighting',price:1890,stock:18,status:'PUBLISHED',category_name:'إضاءة'}]
const filtered=computed(()=>products.value.filter(p=>(!search.value||`${p.name} ${p.sku||''}`.toLowerCase().includes(search.value.toLowerCase()))&&(!status.value||p.status===status.value)&&(!category.value||String(p.category_id)===String(category.value))))
async function load(){loading.value=true;try{const [p,c]=await Promise.all([api.products(),api.categories()]);products.value=p?.data||p||[];categories.value=c?.data||c||[];if(!products.value.length)products.value=fallback}catch{products.value=fallback}finally{loading.value=false}}
onMounted(load)
</script>
<template><div><div class="page-head"><div><span class="eyebrow">CATALOG</span><h1>Products</h1><p>Manage products and assign every product to a dynamic category.</p></div><RouterLink class="button button-blue" to="/products/new">Add Product</RouterLink></div><div class="toolbar"><input v-model="search" placeholder="Search products or SKUs..."><select v-model="status"><option value="">Status: All</option><option value="PUBLISHED">Published</option><option value="DRAFT">Draft</option><option value="ARCHIVED">Archived</option></select><select v-model="category"><option value="">Category: All</option><option v-for="c in categories" :key="c.id" :value="c.id">{{c.name}}</option></select></div><section class="panel table"><div class="table-row header"><span>PRODUCT</span><span>SKU</span><span>CATEGORY</span><span>PRICE</span><span>STOCK</span><span>STATUS</span><span></span></div><div v-if="loading" class="empty-row">Loading products...</div><div v-for="p in filtered" :key="p.id" class="table-row"><span><b>{{p.name}}</b><small>{{p.brand||'VORA'}}</small></span><span>{{p.sku||'—'}}</span><span>{{p.category_name||'—'}}</span><span>{{Number(p.price||0).toLocaleString()}} EGP</span><span>{{p.stock}}</span><span><em :class="['status',String(p.status).toLowerCase()]"><i></i>{{p.status}}</em></span><RouterLink :to="`/products/${p.id}/edit`" class="text-link">Edit</RouterLink></div><div v-if="!loading&&!filtered.length" class="empty-row">No products match your filters.</div></section></div></template>
